FROM node:22-alpine


RUN mkdir -p /app && chown -R node:node /app

WORKDIR /app

USER node

COPY --chown=node:node package*.json ./


RUN npm install


COPY --chown=node:node . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]